### ISSUE TITLE
Fail to download objects 101-1000

### ISSUE THREAD

**Issue by fred206968** [rhgao/ObjectFolder#1]
When I tried to download objects 101-1000 using wget https://download.cs.stanford.edu/viscam/ObjectFolder/ObjectFolder101-1000.tar.gz, I got a 404 error: HTTP request sent, awaiting response... 404 Not Found.

**Comment by rhgao** [comment]
There were some issues with sharing them altogether. It will be shared 100 objects by 100 objects as soon as they are ready.
