### ISSUE TITLE
Can't download the dataset since 201

### ISSUE THREAD

**Issue by xwinks** [rhgao/ObjectFolder#2]
The URL for 201-1000 object is not found.

**Comment by xwinks** [comment]
these URL will get 404 response such as :
https://download.cs.stanford.edu/viscam/ObjectFolder/ObjectFolder201-300.tar.gz
https://download.cs.stanford.edu/viscam/ObjectFolder/ObjectFolder301-400.tar.gz

**Comment by csrqli** [comment]
Same issue. 201-300.tar.gz and previous files work, but the subsequent files don't.

**Comment by rhgao** [comment]
Objects before 500 should all be downloadable now. We are doing some re-organization and verification of the rest of the objects and will share them in the coming weeks. Thank you for your patience.

**Comment by rhgao** [comment]
Solved.
