### ISSUE TITLE
how do we obtain the data for rendering the objects?

### ISSUE THREAD

**Issue by kachiO** [rhgao/ObjectFolder#3]
Specifically, where do we get the following files? 
- `vision_test_file_path`
- `audio_vertices_file_path`
- `audio_forces_file_path`
- `touch_vertices_file_path`
- `touch_gelinfo_file_path`

Are these just randomly sampled?

**Comment by Marjaniiii** [comment]
@kachiO did you find out how we get the following files?

vision_test_file_path
audio_vertices_file_path
audio_forces_file_path
touch_vertices_file_path
touch_gelinfo_file_path
Are these just randomly sampled?
